# Generated by Django 4.1 on 2022-09-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postjob',
            old_name='description',
            new_name='text',
        ),
    ]
