# Generated by Django 4.1 on 2022-09-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_postjob_created_date_postjob_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminUpload', models.FileField(upload_to='media')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
