# Generated by Django 4.1 on 2022-09-13 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_filesadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postjob',
            old_name='text',
            new_name='description',
        ),
    ]
