# Generated by Django 4.1 on 2022-09-13 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_rename_text_postjob_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postjob',
            old_name='description',
            new_name='desc',
        ),
    ]
