# Generated by Django 4.1 on 2022-09-13 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_rename_description_postjob_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postjob',
            old_name='desc',
            new_name='text',
        ),
    ]
