# Generated by Django 4.1 on 2022-09-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_rename_desc_postjob_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='text',
            field=models.CharField(max_length=600),
        ),
    ]
